apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-server
  template:
    metadata:
      labels:
        app: node-server
    spec:
      containers:
      - name: node-server
        image: <your-docker-repo>/node-server:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node-server
spec:
  type: ClusterIP
  selector:
    app: node-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000 